---
kind: pipeline
type: docker
name: generator

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}

steps:
  - name: Install dependencies
    image: registry.cn-hangzhou.aliyuncs.com/rongpengju-pulic-images/goprotoc:2.0
    pull: always
    commands:
      - make install
    volumes:
      - name: deps
        path: /go

#  - name: generator code
#    image: registry.cn-hangzhou.aliyuncs.com/rongpengju-pulic-images/goprotoc:2.0
#    pull: always
#    commands:
#      - make build
#    volumes:
#      - name: deps
#        path: /go

#  - name: push code
#    image: registry.cn-hangzhou.aliyuncs.com/rongpengju-pulic-images/goprotoc:2.0
#    pull: always
#    commands:
#      - make push-to-go-repo
#    volumes:
#      - name: deps
#        path: /go
