---
kind: pipeline
type: docker
name: generator

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}

steps:
  - name: install dependencies
    image: golang:1.19
    pull: always
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - make install
    volumes:
      - name: deps
        path: /go

  - name: generator code
    image: golang:1.19
    pull: always
    commands:
      - make build
    volumes:
      - name: deps
        path: /go

#  - name: push code
#    image: golang:1.19
#    pull: always
#    commands:
#      - make push-to-go-repo
#    volumes:
#      - name: deps
#        path: /go
