---
kind: pipeline
type: docker
name: generator

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request

volumes:
  - name: deps
    temp: {}

steps:
  - name: install dependencies
    image: golang:1.19
    pull: always
    commands:
      - make install
    volumes:
      - name: deps
        path: /go

  - name: generator code
    image: golang:1.19
    pull: always
    commands:
      - make build
    volumes:
      - name: deps
        path: /go

  - name: push code
    image: golang:1.19
    pull: always
    commands:
      - make push-to-go-repo
    volumes:
      - name: deps
        path: /go
