---
kind: pipeline
type: docker
name: generator

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: deps
    temp: {}

steps:
  - name: Install Dependencies
    image: golang:1.19
    pull: always
    commands:
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - make install
    volumes:
      - name: deps
        path: /go

  - name: Generator Code
    image: golang:1.19
    pull: always
    commands:
      - make build
    volumes:
      - name: deps
        path: /go

  - name: Push Code
    image: golang:1.19
    pull: always
    commands:
      - apt install apt-transport-https
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - make push-to-go-repo
    volumes:
      - name: deps
        path: /go
