name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Start install
        run: make install

  build:
    name: build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Start build
        run: make build

  push:
    name: push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Start push
        run: make push-to-go-repo
