name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  execute:
    name: start job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Start install
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make install

      - name: cat version
        run: |
          buf --version

#      - name: cat version
#        run: |
#          protoc --version
#          buf --version
#
#      - name: Start build
#        run: make build
#
#      - name: Start push
#        run: make push-to-go-repo
