name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  execute:
    name: start job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Start install
        run: make install

      - name: cat version
        run: |
          protoc --version
          buf --version

      - name: Start build
        run: make build

      - name: Start push
        run: make push-to-go-repo
