name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  execute:
    name: start job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Start install
        run: make install

      - name: Setup buf env
        run: |
          cp -r /home/runner/go/bin/ /usr/local/bin/
          chmod -R 777 /usr/local/bin/


      - name: cat env
        run: |
          cd /home/runner/go/bin
          ls
          buf --version
          protoc --version

      - name: Start build
        run: make build

      - name: cat generate files
        run: ls -a
#
#      - name: Start push
#        run: make push-to-go-repo