name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
jobs:
  do:
    name: run job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Start install
        run: |
          make install

      - name: Start build
        run: |
          make build

      - name: Start push
        run: |
          make push-to-go-repo
