name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    needs: set
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Start install
        run: |
          make install

  build:
    name: build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Start build
        run: |
          make build

  push:
    name: push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Start push
        run: |
          make push-to-go-repo
