name: Build And Push
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  execute:
    name: start job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Start install
        run: make install

      - name: Setup buf env
        run: |
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$(go env GOBIN)
#          cd /home/runner/go/bin/
#          ls
#          mv /home/runner/go/bin/grpcurl /usr/local/bin/
#          mv /home/runner/go/bin/protoc-gen-connect-go /usr/local/bin/
#          mv /home/runner/go/bin/protoc-gen-go /usr/local/bin/
#          mv /home/runner/go/bin/protoc-gen-go-grpc /usr/local/bin/
#          mv /home/runner/go/bin/buf /usr/local/bin/
#          chmod +x /usr/local/bin/grpcurl
#          chmod +x /usr/local/bin/protoc-gen-connect-go
#          chmod +x /usr/local/bin/protoc-gen-go
#          chmod +x /usr/local/bin/protoc-gen-go-grpc
#          chmod +x /usr/local/bin/buf

      - name: cat sys env
        run: |
          echo $PATH
          go env

      - name: cat env
        run: |
          cd /home/runner/go/bin
          ls
          buf --version
          protoc --version

      - name: Start build
        run: make build

      - name: cat generate files
        run: ls -a
#
#      - name: Start push
#        run: make push-to-go-repo